// auth routes
// signup
POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
    "username": "tonystork",
    "fullName": "Tony Stork",
    "password": "tony123",
    "email": "tonystork@gmail.com"
}

###

// signin
POST http://localhost:5000/api/auth/signin 
Content-Type: application/json

{
    "username": "tonystork",
    "password": "tony123"
}

###
// signout
POST http://localhost:5000/api/auth/signout


###

// getMe
GET http://localhost:5000/api/auth/me


###

// user routes
// get user profile
GET http://localhost:5000/api/user/profile/tonystork

###

// follow or unfollow
POST http://localhost:5000/api/user/follow/66f18d49fc50b0c7672a296b


###

// suggested users

GET http://localhost:5000/api/user/suggested


###

// update profile
PUT http://localhost:5000/api/user/update
Content-Type: application/json

{
    "email": "tonystork123@gmail.com",
    # "currentPassword": "tony1234",
    # "newPassword": "tony123",
    "bio": "I'm tony stork",
    "link": "tonystork.com"
}