// auth routes
// signup
POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
    "username": "tonystork",
    "fullName": "Tony Stork",
    "password": "tony123",
    "email": "tonystork@gmail.com"
}

###

// signin
POST http://localhost:5000/api/auth/signin 
Content-Type: application/json

{
    "username": "harrypotter",
    "password": "harry1234"
}

###
// signout
POST http://localhost:5000/api/auth/signout


###

// getMe
GET http://localhost:5000/api/auth/me


###

// user routes
// get user profile
GET http://localhost:5000/api/user/profile/tonystork

###

// follow or unfollow
POST http://localhost:5000/api/user/follow/66f18d49fc50b0c7672a296b


###

// suggested users

GET http://localhost:5000/api/user/suggested


###

// update profile
PUT http://localhost:5000/api/user/update
Content-Type: application/json

{
    "email": "tonystork123@gmail.com",
    # "currentPassword": "tony1234",
    # "newPassword": "tony123",
    "bio": "I'm tony stork",
    "link": "tonystork.com"
}


###
// post routes
// create post

POST http://localhost:5000/api/post/create
Content-Type: application/json

{
    "text": "My first post"
}


###

// delete post
DELETE http://localhost:5000/api/post/66f4407b9be8ef1a926e0027


###

// comment on post

POST http://localhost:5000/api/post/comment/66f4dd39924e819856a67a9d
Content-Type: application/json

{
    "text": "my first comment"
}


###

// like or unlike post

POST http://localhost:5000/api/post/like/66f4dd39924e819856a67a9d


###

// get all posts

GET http://localhost:5000/api/post/all


###

// get all liked posts
GET http://localhost:5000/api/post/likes/66f2e09e34fd9cae91c1fdd5