export const POSTS = [
  {
    _id: '1',
    text: "Let's build a fullstack WhatsApp clone with NEXT.JS 14 😍",
    img: '/posts/post1.png',
    user: {
      username: 'harrypotter',
      profileImg: '/avatars/boy1.png',
      fullName: 'Harry Potter',
    },
    comments: [
      {
        _id: '1',
        text: 'Nice Tutorial',
        user: {
          username: 'hermionegranger',
          profileImg: '/avatars/girl1.png',
          fullName: 'Hermione Granger',
        },
      },
    ],
    likes: ['6658s891', '6658s892', '6658s893', '6658s894'],
  },
  {
    _id: '2',
    text: 'How you guys doing? 😊',
    user: {
      username: 'ronweasley',
      profileImg: '/avatars/boy2.png',
      fullName: 'Ron Weasley',
    },
    comments: [
      {
        _id: '1',
        text: 'Nice Tutorial',
        user: {
          username: 'lunalovegood',
          profileImg: '/avatars/girl2.png',
          fullName: 'Luna Lovegood',
        },
      },
    ],
    likes: ['6658s891', '6658s892', '6658s893', '6658s894'],
  },
  {
    _id: '3',
    text: 'Astronaut in a room of drawers, generated by Midjourney. 🚀',
    img: '/posts/post2.png',
    user: {
      username: 'nevillelongbottom',
      profileImg: '/avatars/boy3.png',
      fullName: 'Neville Longbottom',
    },
    comments: [],
    likes: [
      '6658s891',
      '6658s892',
      '6658s893',
      '6658s894',
      '6658s895',
      '6658s896',
    ],
  },
  {
    _id: '4',
    text: "I'm learning GO this week. Any tips? 🤔",
    img: '/posts/post3.png',
    user: {
      username: 'oliverwood',
      profileImg: '/avatars/boy3.png',
      fullName: 'Oliver Wood',
    },
    comments: [
      {
        _id: '1',
        text: 'Nice Tutorial',
        user: {
          username: 'ginnyweasley',
          profileImg: '/avatars/girl3.png',
          fullName: 'Ginny Weasley',
        },
      },
    ],
    likes: [
      '6658s891',
      '6658s892',
      '6658s893',
      '6658s894',
      '6658s895',
      '6658s896',
      '6658s897',
      '6658s898',
      '6658s899',
    ],
  },
];

export const USERS_FOR_RIGHT_PANEL = [
  {
    _id: '1',
    fullName: 'Harry Potter',
    username: 'harrypotter',
    profileImg: '/avatars/boy2.png',
  },
  {
    _id: '2',
    fullName: 'Luna Lovegood',
    username: 'luna lovegood',
    profileImg: '/avatars/girl1.png',
  },
  {
    _id: '3',
    fullName: 'Ron Weasley',
    username: 'ronweasley',
    profileImg: '/avatars/boy3.png',
  },
  {
    _id: '4',
    fullName: 'Hermione Granger',
    username: 'hermionegranger',
    profileImg: '/avatars/girl2.png',
  },
];
